apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  annotations:
    imageregistry: https://nub.docker.com/
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - protocol: TCP
      containerPort: 80
