apiVersion: v1
kind: Service
metadata:
  name: hello-node-svc
spec:
  type: NodePort
  selector:
    app: hello-node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30100