apiVersion: v1
kind: Service
metadata:
  name: hello-nasa-svc
spec:
  type: ClusterIP
  clusterIP: 10.100.10.10
  selector:
    app: hello-nasa
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080