apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    env: dev
    tier: frontend 
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - protocol: TCP
      containerPort: 80