apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - protocol: TCP
      containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
    