apiVersion: v1
kind: Service
metadata:
  name: nasa-node-svc
spec:
  selector:
    app: nasa-node
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8082
  