apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app: simple-pod
spec:
  containers:
  - name: simple-container
    image: arisu1000/simple-container-app:latest
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: simple-svc
spec:
  type: NodePort
  selector:
    app: simple-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30100