apiVersion: v1
kind: ReplicationController
metadata:
  name: testpod
spec:
  replicas: 3
  selector:
    app: hpe
  template:
    metadata: 
      name: hpe
      labels:
        app: hpe
    spec:
      containers:
      - name: test
        image: smlinux/appjs
        ports:
        - containerPort: 8080