apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
  labels:
    app: simple-app
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: simple-app
  template:
    metadata: 
      name: simple-app
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: arisu1000/simple-container-app:latest
        ports:
        - containerPort: 8080
      tolerations:
      - key: 'key01'
        operator: 'Equal'
        value: 'value01'
        effect: 'NoSchedule'
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app
spec:
  type: NodePort
  selector:
    app: simple-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30100