apiVersion: v1
kind: Pod # 리소스 타입
metadata:
  name: busybox-pod
  labels:
    app: busybox
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ['sh', '-c', 'echo Hello busybox && sleep 3600']