apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    command: ['bash', '-c', 'echo Hello ubuntu! && sleep 3600']